### ISSUE TITLE
PHP Fatal error - Serialization of 'CURLFile' is not allowed

### ISSUE THREAD

**Issue by vmanthos** [wp-media/imagify-tools#44]
The following popped up in the `debug.log`:
```PHP
PHP Fatal error:  Uncaught Exception: Serialization of 'CURLFile' is not allowed in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/functions/common.php:101
Stack trace:
#0 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/functions/common.php(101): serialize()
#1 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(653): imagify_tools_compress_data()
#2 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(609): IMGT_Logs::insert_log()
#3 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(520): IMGT_Logs->save_logs()
#4 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): IMGT_Logs->save_current_logs()
#5 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-includes/load.php(1144): do_action()
#8 [internal function]: shutdown_action_hook()
#9 {main}
  thrown in /var/www/vasilis.rocketlabsqa.ovh/htdocs/wp-content/plugins/imagify-tools/functions/common.php on line 101
```

I'm not sure how to reproduce this except by having Imagify Tools enabled alongside Imagify.

**Comment by PPNSteve** [comment]
Seeing this issue as well:

[24-Mar-2024 18:26:54 UTC] PHP Fatal error:  Uncaught Exception: Serialization of 'CURLFile' is not allowed in /home/infinite/public_html/wp-content/plugins/imagify-tools/functions/common.php:101
Stack trace:
#0 /home/infinite/public_html/wp-content/plugins/imagify-tools/functions/common.php(101): serialize(Array)
#1 /home/infinite/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(653): imagify_tools_compress_data(Array)
#2 /home/infinite/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(609): IMGT_Logs::insert_log(Array, Array)
#3 /home/infinite/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(520): IMGT_Logs->save_logs(Array)
#4 /home/infinite/public_html/wp-includes/class-wp-hook.php(324): IMGT_Logs->save_current_logs('')
#5 /home/infinite/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /home/infinite/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/infinite/public_html/wp-includes/load.php(1260): do_action('shutdown')
#8 [internal function]: shutdown_action_hook()
#9 {main}
  thrown in /home/infinite/public_html/wp-content/plugins/imagify-tools/functions/common.php on line 101
